import { defineStore } from 'pinia';
import { Project } from 'src/models/interfaces/projects';

export const useProjectsStore = defineStore('projects', {
  state: () => ({
    projects: [
      {
        label: 'Bibliothèque de composants Nui',
        name: 'nuiLibrary',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Library',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Elise',
        name: 'elise',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#0B7A98',
          gradientEllipseLeft: '#0B7A98',
          gradientCircleRight: '#0B7A98',
          gradientEllipse1Right: '#0B7A98',
          gradientEllipse2Right: '#C6DFE7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#0B7A98',
          gradientEllipse1Right: '#0B7A98',
          gradientEllipse2Right: '#C6DFE7',
        },
        category: 'Application web',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Portfolio',
        name: 'portfolio',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#42b883',
          gradientEllipseLeft: '#0ebbd2',
          gradientCircleRight: '#02faaf',
          gradientEllipse1Right: '#00c2ff',
          gradientEllipse2Right: '#0ebbd2',
        },
        colorLight: {
          primary: '#42b883',
          gradientEllipseLeft: '#0ebbd2',
          gradientCircleRight: '#02faaf',
          gradientEllipse1Right: '#00c2ff',
          gradientEllipse2Right: '#0ebbd2',
        },
        category: 'Application PWA',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: "Fée d'encre",
        name: 'feedencre',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#c1c79a',
          gradientEllipseLeft: '#c1c79a',
          gradientCircleRight: '#c1c79a',
          gradientEllipse1Right: '#c1c79a',
          gradientEllipse2Right: '#c1c79a',
        },
        colorLight: {
          primary: '#636b3a',
          gradientEllipseLeft: '#636b3a',
          gradientCircleRight: '#636b3a',
          gradientEllipse1Right: '#636b3a',
          gradientEllipse2Right: '#636b3a',
        },
        category: 'Application PWA',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Maths United',
        name: 'mathsUnited',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#F6B26D',
          gradientEllipseLeft: '#F6B26D',
          gradientCircleRight: '#12805B',
          gradientEllipse1Right: '#12805B',
          gradientEllipse2Right: '#064252',
        },
        colorLight: {
          primary: '#12805B',
          gradientEllipseLeft: '#F6B26D',
          gradientCircleRight: '#12805B',
          gradientEllipse1Right: '#12805B',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application PWA',
        year: '2024',
        company: 'Maths united',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Logbook',
        name: 'logbook',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#8A6E4E',
          gradientEllipseLeft: '#8A6E4E',
          gradientCircleRight: '#8A6E4E',
          gradientEllipse1Right: '#f1f3f3',
          gradientEllipse2Right: '#f1f3f3',
        },
        colorLight: {
          primary: '#8A6E4E',
          gradientEllipseLeft: '#8A6E4E',
          gradientCircleRight: '#8A6E4E',
          gradientEllipse1Right: '#000000',
          gradientEllipse2Right: '#000000',
        },
        category: 'Application PWA',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Sympathy',
        name: 'sympathy',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application mobile',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Yu-gi-oh Counter',
        name: 'yugiohCounter',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application mobile',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'For season',
        name: 'forSeason',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application web / mobile',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Remake home VR/AR',
        name: 'remakeHome',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'VR / AR',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Portail de notification',
        name: 'portailDeNotification',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application web',
        year: '2024',
        company: 'Neoledge',
        personal: true,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'LGO2 Alert',
        name: 'lgo2Alert',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application web',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Plan de guerre Auchan Drive',
        name: 'pgAuchanDrive',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application web',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Running',
        name: 'running',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application de bureau',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Comunity',
        name: 'comunity',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Gestion de projet',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Distance de séparation foudre',
        name: 'dsf',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application de bureau',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'Camera configuration',
        name: 'cameraConfiguration',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application de bureau',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
      {
        label: 'VPR',
        name: 'vpr',
        desc: '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto fuga quae veritatis blanditiis sequi id expedita amet esse aspernatur! Iure, doloribus!</p>',
        links: [
          {
            title: 'Accès au site',
            path: 'https://www.design.neoledge.com',
          },
        ],
        colorDark: {
          primary: '#C6E0E7',
          gradientEllipseLeft: '#C6E0E7',
          gradientCircleRight: '#C6E0E7',
          gradientEllipse1Right: '#C6E0E7',
          gradientEllipse2Right: '#C6E0E7',
        },
        colorLight: {
          primary: '#064252',
          gradientEllipseLeft: '#064252',
          gradientCircleRight: '#064252',
          gradientEllipse1Right: '#064252',
          gradientEllipse2Right: '#064252',
        },
        category: 'Application de bureau',
        year: '2024',
        company: 'Neoledge',
        personal: false,
        tech: ['HTML', 'SCSS', 'JAVASCRIPT'],
      },
    ],
  }),
  getters: {
    getPersonalProject(state) {
      return state.projects.filter((project: Project) => project.personal);
    },
    getJobProject(state) {
      return state.projects.filter((project: Project) => !project.personal);
    },
  },
});
